"""Universal document renderer: Markdown -> HTML -> {PDF, DOCX}.

Converts LLM-generated markdown into professionally styled PDF (via WeasyPrint)
or DOCX (via htmldocx) documents. CSS logic lives in style_engine.py;
this module focuses on HTML assembly and format-specific output.
"""

import html
import re
from datetime import date

import markdown

from .style_engine import build_css

# Regex to extract heading hex colors from custom CSS for DOCX post-processing
_HEADING_COLOR_RE = re.compile(
    r'h[1-3][^{]*\{[^}]*color:\s*(#[0-9a-fA-F]{6})', re.IGNORECASE,
)


def _build_html(title: str, disease: str, markdown_content: str,
                theme: str = "default", custom_css: str = "") -> str:
    """Convert markdown to a complete, styled HTML document."""
    # Auto-landscape for wide tables (>7 columns)
    max_pipes = max((line.count("|") for line in markdown_content.split("\n")
                     if "|" in line), default=0)
    page_size = "A4 landscape" if max_pipes > 7 else "A4"

    css = build_css(theme, page_size, custom_css)

    body_html = markdown.markdown(
        markdown_content,
        extensions=["tables", "fenced_code", "toc"],
    )

    header_parts = [f"<h1>{html.escape(title)}</h1>"]
    if disease:
        header_parts.append(f'<p class="disease">Disease context: {html.escape(disease)}</p>')
    header_parts.append(f'<p class="dateline">Generated {date.today().isoformat()}</p>')

    return (
        f"<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>"
        f"<style>{css}</style></head><body>"
        f'<div class="report-header">{chr(10).join(header_parts)}</div>'
        f'<main class="report-body">{body_html}</main>'
        f'<div class="report-footer">Generated by Agentic AI Platform</div>'
        f"</body></html>"
    )


def render_pdf(title: str, disease: str, content: str,
               output_path: str, theme: str = "default",
               custom_css: str = "") -> None:
    """Render markdown content to a styled PDF via WeasyPrint."""
    from weasyprint import HTML
    html = _build_html(title, disease, content, theme, custom_css)
    HTML(string=html).write_pdf(output_path)


def render_docx(title: str, disease: str, content: str,
                output_path: str, theme: str = "default",
                custom_css: str = "") -> None:
    """Render markdown content to a DOCX via htmldocx with proportional table columns."""
    from docx.shared import Inches
    from docx.shared import RGBColor
    from htmldocx import HtmlToDocx

    html = _build_html(title, disease, content, theme, custom_css)
    parser = HtmlToDocx()
    parser.table_style = "TableGrid"
    doc = parser.parse_html_string(html)

    # Post-process: proportional column widths based on content length
    for table in doc.tables:
        col_widths = [1.0] * len(table.columns)
        for row in table.rows:
            for i, cell in enumerate(row.cells):
                if i < len(col_widths):
                    col_widths[i] = max(col_widths[i], len(cell.text) * 0.08)
        for row in table.rows:
            for i, cell in enumerate(row.cells):
                if i < len(col_widths):
                    cell.width = Inches(max(0.8, min(4.0, col_widths[i])))
        # Repeat header row on page breaks
        try:
            tbl_pr = table._tbl.tblPr
            if tbl_pr is not None:
                from docx.oxml.ns import qn
                for row in table.rows[:1]:
                    tr = row._tr
                    trPr = tr.get_or_add_trPr()
                    trPr.append(tr.makeelement(qn('w:tblHeader'), {}))
        except Exception:
            pass

    # Apply base font and paragraph spacing to Normal style
    try:
        from docx.shared import Pt
        style = doc.styles['Normal']
        style.font.size = Pt(11)
        style.font.name = 'Calibri'
        style.paragraph_format.space_after = Pt(6)
    except Exception:
        pass

    # Best-effort: apply heading colors from custom CSS to DOCX paragraphs
    if custom_css:
        hex_match = _HEADING_COLOR_RE.search(custom_css)
        if hex_match:
            hex_val = hex_match.group(1).lstrip("#")
            try:
                rgb = RGBColor(int(hex_val[:2], 16), int(hex_val[2:4], 16), int(hex_val[4:6], 16))
                for para in doc.paragraphs:
                    if para.style and para.style.name and para.style.name.startswith("Heading"):
                        for run in para.runs:
                            run.font.color.rgb = rgb
            except (ValueError, IndexError):
                pass

    doc.save(output_path)
