"""Structured Report Viewer — interactive display of analysis reports.

Renders Markdown reports generated by the supervisor reporting engine with:
  - Table of contents sidebar navigation
  - Section-by-section display with collapsible evidence cards
  - Confidence badges (colour-coded)
  - Conflict warnings panel
  - Download buttons (MD / PDF / DOCX)
  - Section search / filter
"""

import os
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# Path setup — same pattern as app.py
project_root = Path(__file__).resolve().parent.parent.parent.parent
sys.path.insert(0, str(project_root))

import streamlit as st

# ── Page config ──
st.set_page_config(
    page_title="📊 Structured Report Viewer",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ============================================================================
# CUSTOM CSS
# ============================================================================

st.markdown("""
<style>
    /* Evidence badge styles */
    .badge-high {
        background: #059669; color: white;
        padding: 2px 8px; border-radius: 10px; font-size: 0.75em; font-weight: 600;
    }
    .badge-medium {
        background: #d97706; color: white;
        padding: 2px 8px; border-radius: 10px; font-size: 0.75em; font-weight: 600;
    }
    .badge-low {
        background: #6b7280; color: white;
        padding: 2px 8px; border-radius: 10px; font-size: 0.75em; font-weight: 600;
    }
    .badge-flagged {
        background: #dc2626; color: white;
        padding: 2px 8px; border-radius: 10px; font-size: 0.75em; font-weight: 600;
    }

    /* Conflict warning box */
    .conflict-box {
        background: #fef3c7; border-left: 4px solid #f59e0b;
        padding: 12px; border-radius: 0 8px 8px 0; margin: 8px 0;
    }

    /* Section card */
    .section-card {
        background: white; border: 1px solid #e5e7eb;
        border-radius: 12px; padding: 20px; margin: 12px 0;
        box-shadow: 0 1px 3px rgba(0,0,0,0.06);
    }

    /* TOC link active */
    .toc-active {
        font-weight: 700; color: #2563eb;
    }

    /* API enrichment badge */
    .badge-api {
        background: #8b5cf6; color: white;
        padding: 2px 6px; border-radius: 8px; font-size: 0.7em; font-weight: 500;
    }

    /* Table styling */
    .report-table th { background: #f1f5f9; }
</style>
""", unsafe_allow_html=True)


# ============================================================================
# REPORT PARSING
# ============================================================================

def _parse_markdown_sections(md_text: str) -> List[Dict]:
    """Parse a Markdown report into structured sections.

    Returns a list of dicts with keys: level, title, anchor, body.
    """
    sections = []
    current: Optional[Dict] = None
    body_lines: List[str] = []

    for line in md_text.split("\n"):
        heading_match = re.match(r"^(#{1,4})\s+(.+)", line)
        if heading_match:
            # Flush previous section
            if current is not None:
                current["body"] = "\n".join(body_lines).strip()
                sections.append(current)

            level = len(heading_match.group(1))
            title = heading_match.group(2).strip()
            anchor = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
            current = {"level": level, "title": title, "anchor": anchor, "body": ""}
            body_lines = []
        else:
            body_lines.append(line)

    # Flush last section
    if current is not None:
        current["body"] = "\n".join(body_lines).strip()
        sections.append(current)

    return sections


def _extract_tables(body: str) -> Tuple[str, List[List[List[str]]]]:
    """Extract Markdown pipe tables from section body.

    Returns (body_without_tables, list_of_tables).
    Each table is [[headers], [row1], [row2], ...].
    """
    tables = []
    non_table_lines = []
    table_lines: List[str] = []
    in_table = False

    for line in body.split("\n"):
        stripped = line.strip()
        if "|" in stripped and stripped.startswith("|"):
            table_lines.append(stripped)
            in_table = True
        else:
            if in_table and table_lines:
                table = _parse_pipe_table(table_lines)
                if table:
                    tables.append(table)
                table_lines = []
                in_table = False
            non_table_lines.append(line)

    # Flush trailing table
    if table_lines:
        table = _parse_pipe_table(table_lines)
        if table:
            tables.append(table)

    return "\n".join(non_table_lines), tables


def _parse_pipe_table(lines: List[str]) -> Optional[List[List[str]]]:
    """Parse pipe-delimited Markdown table lines into rows."""
    if len(lines) < 2:
        return None
    rows = []
    for i, line in enumerate(lines):
        cells = [c.strip() for c in line.strip("|").split("|")]
        # Skip separator row (---+)
        if all(re.match(r"^-+$", c.strip()) for c in cells):
            continue
        rows.append(cells)
    return rows if len(rows) >= 1 else None


def _detect_api_tables(body: str) -> List[str]:
    """Detect table captions that came from API enrichment."""
    api_markers = []
    captions = re.findall(r"\*\*(.+?)\*\*", body)
    for cap in captions:
        lower = cap.lower()
        if any(kw in lower for kw in ("ensembl", "string", "reactome", "chembl",
                                       "openfda", "faers", "dgidb", "clinical trial")):
            api_markers.append(cap)
    return api_markers


# ============================================================================
# REPORT DISCOVERY
# ============================================================================

def _find_reports() -> List[Path]:
    """Find all structured report .md files."""
    search_dirs = [
        Path("agentic_ai_wf/shared/reports/structured_reports"),
        Path(project_root / "agentic_ai_wf" / "shared" / "reports" / "structured_reports"),
    ]
    reports = []
    for d in search_dirs:
        if d.exists():
            reports.extend(sorted(d.rglob("*.md"), reverse=True))

    # Also check session state for a direct path
    if "conversation" in st.session_state:
        conv = st.session_state.get("conversation")
        if conv and hasattr(conv, "workflow_state") and conv.workflow_state:
            md_path = conv.workflow_state.get("structured_report_md_path")
            if md_path:
                p = Path(md_path)
                if p.exists() and p not in reports:
                    reports.insert(0, p)

    return reports


def _read_report(path: Path) -> str:
    """Read a report file with error handling."""
    try:
        return path.read_text(encoding="utf-8")
    except Exception as e:
        return f"**Error reading report:** {e}"


# ============================================================================
# RENDERING HELPERS
# ============================================================================

def _render_evidence_badge(confidence: str) -> str:
    css_class = f"badge-{confidence.lower()}"
    label = confidence.upper()
    return f'<span class="{css_class}">{label}</span>'


def _render_section(section: Dict, section_idx: int) -> None:
    """Render a single report section with tables and evidence."""
    title = section["title"]
    body = section["body"]

    if not body and section["level"] == 1:
        # Top-level title — render as main heading
        st.markdown(f"# {title}")
        if body:
            st.markdown(body)
        return

    # Section container
    heading_level = min(section["level"], 4)
    st.markdown(f"{'#' * heading_level} {title}", anchor=section["anchor"])

    if not body:
        st.caption("*No content for this section.*")
        return

    # Check for API-enriched tables
    api_tables = _detect_api_tables(body)

    # Extract tables from body
    text_body, tables = _extract_tables(body)

    # Render text body
    if text_body.strip():
        st.markdown(text_body)

    # Render tables
    for idx, table_data in enumerate(tables):
        if len(table_data) < 2:
            continue
        headers = table_data[0]
        rows = table_data[1:]

        # Check if this is an API-enriched table
        is_api = idx < len(api_tables)

        if is_api:
            col1, col2 = st.columns([0.95, 0.05])
            with col1:
                st.caption(api_tables[idx] if idx < len(api_tables) else "")
            with col2:
                st.markdown('<span class="badge-api">API</span>', unsafe_allow_html=True)

        import pandas as pd
        df = pd.DataFrame(rows, columns=headers)
        st.dataframe(df, use_container_width=True, hide_index=True)


def _render_conflicts(md_text: str) -> None:
    """Render cross-module conflict section if present."""
    conflict_match = re.search(
        r"## Cross-Module Conflicts\n(.+?)(?=\n## |\Z)", md_text, re.DOTALL,
    )
    if not conflict_match:
        return

    st.markdown("---")
    st.markdown("### ⚠️ Cross-Module Conflicts")
    conflicts = conflict_match.group(1).strip().split("\n")
    for c in conflicts:
        c = c.strip()
        if c.startswith("- "):
            st.markdown(
                f'<div class="conflict-box">{c[2:]}</div>',
                unsafe_allow_html=True,
            )


# ============================================================================
# MAIN PAGE
# ============================================================================

st.markdown("# 📊 Structured Report Viewer")
st.markdown("*Browse and explore structured analysis reports with evidence traceability*")
st.markdown("---")

# ── Sidebar: Report selection + TOC ──
with st.sidebar:
    st.markdown("### 📑 Reports")

    reports = _find_reports()

    if not reports:
        st.info("No structured reports found yet. Run an analysis and request a structured report.")
        st.markdown("---")
        st.markdown(
            "**How to generate a report:**\n\n"
            "Ask the assistant: *\"Generate a structured report\"* after running analyses."
        )
        st.stop()

    # Report selector
    report_options = {
        f"{p.parent.name}/{p.name}": p for p in reports
    }
    selected_label = st.selectbox(
        "Select report",
        options=list(report_options.keys()),
        index=0,
    )
    selected_path = report_options[selected_label]

    st.markdown("---")

    # Read and parse for TOC
    md_text = _read_report(selected_path)
    sections = _parse_markdown_sections(md_text)

    st.markdown("### 📋 Table of Contents")
    for sec in sections:
        indent = "&nbsp;&nbsp;" * max(0, sec["level"] - 1)
        anchor = sec["anchor"]
        st.markdown(
            f'{indent}[{sec["title"]}](#{anchor})',
            unsafe_allow_html=True,
        )

    st.markdown("---")

    # Download buttons
    st.markdown("### 📥 Download")

    st.download_button(
        label="📄 Download Markdown",
        data=md_text,
        file_name=selected_path.name,
        mime="text/markdown",
        use_container_width=True,
    )

    # Check for companion PDF/DOCX
    for ext, label, mime in [
        (".pdf", "📕 Download PDF", "application/pdf"),
        (".docx", "📘 Download DOCX", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
    ]:
        companion = selected_path.with_suffix(ext)
        if companion.exists():
            try:
                with open(companion, "rb") as f:
                    st.download_button(
                        label=label,
                        data=f.read(),
                        file_name=companion.name,
                        mime=mime,
                        use_container_width=True,
                    )
            except Exception:
                pass

    st.markdown("---")

    # Section filter
    st.markdown("### 🔍 Filter")
    search_term = st.text_input("Search sections", placeholder="e.g. pathway, drug")

# ── Main content area ──
if not md_text:
    st.warning("Could not read the selected report.")
    st.stop()

# Report metadata bar
col1, col2, col3 = st.columns(3)
with col1:
    st.metric("Sections", len(sections))
with col2:
    # Count tables
    table_count = md_text.count("| ---")
    st.metric("Tables", table_count)
with col3:
    # File size
    size_kb = selected_path.stat().st_size / 1024
    st.metric("Size", f"{size_kb:.1f} KB")

st.markdown("---")

# Display mode tabs
tab_rendered, tab_raw = st.tabs(["📊 Interactive View", "📝 Raw Markdown"])

with tab_rendered:
    for idx, section in enumerate(sections):
        # Apply search filter
        if search_term:
            if (search_term.lower() not in section["title"].lower()
                    and search_term.lower() not in section["body"].lower()):
                continue

        _render_section(section, idx)

    # Conflicts panel
    _render_conflicts(md_text)

with tab_raw:
    st.code(md_text, language="markdown")
